# Generated by Django 4.2 on 2023-04-24 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
